### ISSUE TITLE
C++ implementation

### ISSUE THREAD

**Issue by sublimator** [cryptocoinjs/base-x#11]
It would be great to have an efficient C++ implementation for server usage. I'm not sure the logistics of that, but just throwing the idea out there.

**Comment by dcousens** [comment]
@sublimator I guess so,  but the cost of maintaining that could be more than it is worth.
**Could be**.

**Comment by sublimator** [comment]
Seems like something that wouldn't really need much maintenance? /me speaks having never written a native node module.

**Comment by jprichardson** [comment]
> I guess so, but the cost of maintaining that could be more than it is worth.

This is why I'd be against it. 

If a person is that concerned about speed, they probably shouldn't be using Node.js then. I'd wager that the speed increase for this algorithm would be in the single digits... it may even take a hit as buffers are now handled differently, so proxying them over to C++ land may actually take a hit on performance. This is all conjecture, but this would be one of the single lowest items on my priority list at the moment :( 

Not to say that I'd always be opposed, just for now.

**Comment by sublimator** [comment]
I don't buy the old "you shouldn't be using node if you care about speed"
argument. Node is convenient. Speed is nice to have. But I totally
understand why this is in no way something you'd spend time on inplementing
yourself. If I looked into this personally (just copied the code from
bitcoin for a start) and it provided a measurable speedup would you
consider a patch?

**Comment by dcousens** [comment]
> If I looked into this personally (just copied the code from
bitcoin for a start) and it provided a measurable speedup would you
consider a patch?

I would consider a patch,  but again,  it depends on the complexity.

**Comment by sublimator** [comment]
Fair enough :)

**Comment by jprichardson** [comment]
> I don't buy the old "you shouldn't be using node if you care about speed"
argument. 

That wasn't my argument :)

My point was:

> If a person is that concerned about speed, they probably shouldn't be using Node.js then

The difference is **that concerned** - so I understand how the confusion came about. Subtle, but important distinction though.

i.e....

Of course, a dev should care about speed, and Node.js is a fine platform for high-performant applications. My point was, that if a person cares so much about speed that they're willing to use a text encoding algorithm written in C++ to achieve minuscule gains over one written with pure JavaScript, maybe Node.js isn't the appropriate platform. I could most certainly be wrong on the gains though.

Here's what I'd like to see:

1. A benchmark comparison on the difference between a pure Node.js app against a pure C++ app, specifically base-58 encoding.
2. After `1.`, I'd then be interested on the same benchmark tests, but instead of the pure C++ app, modify so that it's a Node.js app with the base-58 encoding written in C++.

Pure conjecture: native C++ Node.js module in `2.` will be slower or slightly faster (single digit percentage) than the pure JS version.

**Comment by sublimator** [comment]
Fair enough, sorry for getting confused as to your position.

TBH I didn't give it much thought beyond "create-hash seems to use node
native modules for hashing where possible. Gee it would be nifty if there
was a similar speedup module for base-x"

**Comment by fanatid** [comment]
I think that I got at least +50% performance improvement, but instead `encode` was slowest in 4 times... may be I made something wrong [code here](https://github.com/fanatid/base-x/blob/addon/src/basex.cc#L51), but with #16 I think C++ implementation is not relevant.

**Comment by sublimator** [comment]
Never know if ya never go :)

**Comment by fanatid** [comment]
Code in branch [feature/cpp-implementation](https://github.com/cryptocoinjs/base-x/tree/feature/cpp-implementation).
Going to close this issue. If somebody want continue with this -- please reopen :)
