### ISSUE TITLE
TS declaration file introduces breaking change

### ISSUE THREAD

**Issue by tjwelde** [cryptocoinjs/base-x#59]
The included https://github.com/cryptocoinjs/base-x/blob/master/src/index.d.ts differs from the one at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/base-x/index.d.ts, which means, this introduces a breaking change.
Other packages (like bs58) use `^3.0.2` as their version string for this package, which will install 3.0.6 and break, because the other package doesn't expect such a breaking change in a patch release.

I would suggest unpublishing v3.0.6 and republishing it as 4.0.0, or overwriting v3.0.6 with the type definition of DefinitelyTyped.

Another more complicated option would be to overwrite 3.0.6 with 3.0.5 and republishing the package with your new typescript declaration under 4.0.0

**Comment by junderw** [comment]
Could you provide reproduction steps for your issue?

I have tried installing old version + DT types and manually changing to ^ and seeing if anything breaks.

Nothing broke.

If you can provide with steps to reproduce the error, I will look into it.

**Comment by junderw** [comment]
I asked a few people who are more experienced in TypeScript than I am, and they can not reproduce the issue.

Yes. If you look at the DefinitelyTyped repo, they try to export a specifically named item of the namespace, and it doesn't exist in our definitions as that name.

However, they have the DefinitelyTyped @types/base-x as a dependency and at build time if I run debug I can see TypeScript looks at the given types, sees a problem, then goes looking for @types/base-x which is installed due to the dependency in @types/bs58 and it transpiles fine.

The easiest way to fix this would be adding type definitions to all related libraries.

**Comment by junderw** [comment]
I've gone ahead and added the interface name to a new patch which should fix the issues you are experiencing.

I would still be interested in any steps you could give to reproduce the issue.

**Comment by junderw** [comment]
Published v3.0.7 which should fix the issue. Please check on your end.

**Comment by tjwelde** [comment]
Hi @junderw thank you for the fast fix.
To reproduce the issue, I made a repo you can check out: https://github.com/tjwelde/bs58-typescript-bug

It just uses bs58 and requires base-x in the version 3.0.6
If you run `npx tsc`, or `./node_module/.bin/tsc`, you should get the error.

Very interesting, that Typescript tries to resolve the conflict with the DefinetelyTyped types, in your tried example. I am curious, if the example in my repo works for you.

**Comment by tjwelde** [comment]
What were the steps you did, where typescript is trying to resolve the conflict of multiple types and uses the DefinetelyTyped ones?

**Comment by junderw** [comment]
This is weird... the results are not consistent for me.

Running with `--traceResolution` shows that it's picking up both... and I don't know what causes it to choose one over the other.

Your repro steps did fail to build, though. If I try doing things like remove base-x as a direct dependency to your repo, or use npm run scripts instead of the command directly it was working and not working intermittently... removing strict also made it work, then adding strict back and it still worked.

it is very wonky... but imo, we should be the ones to manage the type definitions. I have a PR on bs58 and will consider doing something similar for bs58check.

```
======== Resolving module 'base-x' from '/tmp/bs58-typescript-bug/node_modules/@types/bs58/index.d.ts'. ========
Loading module 'base-x' from 'node_modules' folder, target file type 'TypeScript'.
Found 'package.json' at '/tmp/bs58-typescript-bug/node_modules/base-x/package.json'.
File '/tmp/bs58-typescript-bug/node_modules/base-x.ts' does not exist.
File '/tmp/bs58-typescript-bug/node_modules/base-x.tsx' does not exist.
File '/tmp/bs58-typescript-bug/node_modules/base-x.d.ts' does not exist.
'package.json' has 'types' field 'src/index.d.ts' that references '/tmp/bs58-typescript-bug/node_modules/base-x/src/index.d.ts'.
File '/tmp/bs58-typescript-bug/node_modules/base-x/src/index.d.ts' exist - use it as a name resolution result.
Resolving real path for '/tmp/bs58-typescript-bug/node_modules/base-x/src/index.d.ts', result '/tmp/bs58-typescript-bug/node_modules/base-x/src/index.d.ts'.
======== Module name 'base-x' was successfully resolved to '/tmp/bs58-typescript-bug/node_modules/base-x/src/index.d.ts' with Package ID 'base-x/src/index.d.ts@3.0.6'. ========

======== Resolving type reference directive 'base-x', containing file '/tmp/bs58-typescript-bug/__inferred type names__.ts', root directory '/tmp/bs58-typescript-bug/node_modules/@types'. ========
Found 'package.json' at '/tmp/bs58-typescript-bug/node_modules/@types/base-x/package.json'.
'package.json' has 'types' field 'index' that references '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index'.
File '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index' does not exist.
Loading module as file / folder, candidate module location '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index', target file type 'TypeScript'.
File '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index.ts' does not exist.
File '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index.tsx' does not exist.
File '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index.d.ts' exist - use it as a name resolution result.
Resolving real path for '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index.d.ts', result '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index.d.ts'.
======== Type reference directive 'base-x' was successfully resolved to '/tmp/bs58-typescript-bug/node_modules/@types/base-x/index.d.ts' with Package ID '@types/base-x/index.d.ts@3.0.0', primary: true. ========
```
